// Generated by gencpp from file my_service/FindDeterminantResponse.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_FINDDETERMINANTRESPONSE_H
#define MY_SERVICE_MESSAGE_FINDDETERMINANTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct FindDeterminantResponse_
{
  typedef FindDeterminantResponse_<ContainerAllocator> Type;

  FindDeterminantResponse_()
    : determinant(0.0)  {
    }
  FindDeterminantResponse_(const ContainerAllocator& _alloc)
    : determinant(0.0)  {
  (void)_alloc;
    }



   typedef float _determinant_type;
  _determinant_type determinant;





  typedef boost::shared_ptr< ::my_service::FindDeterminantResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::FindDeterminantResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FindDeterminantResponse_

typedef ::my_service::FindDeterminantResponse_<std::allocator<void> > FindDeterminantResponse;

typedef boost::shared_ptr< ::my_service::FindDeterminantResponse > FindDeterminantResponsePtr;
typedef boost::shared_ptr< ::my_service::FindDeterminantResponse const> FindDeterminantResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::FindDeterminantResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::FindDeterminantResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_service::FindDeterminantResponse_<ContainerAllocator1> & lhs, const ::my_service::FindDeterminantResponse_<ContainerAllocator2> & rhs)
{
  return lhs.determinant == rhs.determinant;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_service::FindDeterminantResponse_<ContainerAllocator1> & lhs, const ::my_service::FindDeterminantResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_service::FindDeterminantResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::FindDeterminantResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::FindDeterminantResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::FindDeterminantResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::FindDeterminantResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::FindDeterminantResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::FindDeterminantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dff9b0e4bdfce5c55d0b0a1ea9ff1dc";
  }

  static const char* value(const ::my_service::FindDeterminantResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dff9b0e4bdfce5cULL;
  static const uint64_t static_value2 = 0x55d0b0a1ea9ff1dcULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::FindDeterminantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/FindDeterminantResponse";
  }

  static const char* value(const ::my_service::FindDeterminantResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::FindDeterminantResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 determinant\n"
"\n"
;
  }

  static const char* value(const ::my_service::FindDeterminantResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::FindDeterminantResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.determinant);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindDeterminantResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::FindDeterminantResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::FindDeterminantResponse_<ContainerAllocator>& v)
  {
    s << indent << "determinant: ";
    Printer<float>::stream(s, indent + "  ", v.determinant);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_FINDDETERMINANTRESPONSE_H
