// Generated by gencpp from file my_service/FindDeterminant.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_FINDDETERMINANT_H
#define MY_SERVICE_MESSAGE_FINDDETERMINANT_H

#include <ros/service_traits.h>


#include <my_service/FindDeterminantRequest.h>
#include <my_service/FindDeterminantResponse.h>


namespace my_service
{

struct FindDeterminant
{

typedef FindDeterminantRequest Request;
typedef FindDeterminantResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindDeterminant
} // namespace my_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_service::FindDeterminant > {
  static const char* value()
  {
    return "bd8356770a8b4b909232e44a583097d8";
  }

  static const char* value(const ::my_service::FindDeterminant&) { return value(); }
};

template<>
struct DataType< ::my_service::FindDeterminant > {
  static const char* value()
  {
    return "my_service/FindDeterminant";
  }

  static const char* value(const ::my_service::FindDeterminant&) { return value(); }
};


// service_traits::MD5Sum< ::my_service::FindDeterminantRequest> should match
// service_traits::MD5Sum< ::my_service::FindDeterminant >
template<>
struct MD5Sum< ::my_service::FindDeterminantRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_service::FindDeterminant >::value();
  }
  static const char* value(const ::my_service::FindDeterminantRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_service::FindDeterminantRequest> should match
// service_traits::DataType< ::my_service::FindDeterminant >
template<>
struct DataType< ::my_service::FindDeterminantRequest>
{
  static const char* value()
  {
    return DataType< ::my_service::FindDeterminant >::value();
  }
  static const char* value(const ::my_service::FindDeterminantRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_service::FindDeterminantResponse> should match
// service_traits::MD5Sum< ::my_service::FindDeterminant >
template<>
struct MD5Sum< ::my_service::FindDeterminantResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_service::FindDeterminant >::value();
  }
  static const char* value(const ::my_service::FindDeterminantResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_service::FindDeterminantResponse> should match
// service_traits::DataType< ::my_service::FindDeterminant >
template<>
struct DataType< ::my_service::FindDeterminantResponse>
{
  static const char* value()
  {
    return DataType< ::my_service::FindDeterminant >::value();
  }
  static const char* value(const ::my_service::FindDeterminantResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SERVICE_MESSAGE_FINDDETERMINANT_H
